spring:
  application:
    name: curionest-api
  profiles:
    active: h2

server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: h2
  datasource:
    url: jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres.kubdheqqhkegxgwodrpj
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true

---
spring:
  config:
    activate:
      on-profile: supabase
  datasource:
    url: ${SUPABASE_DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${SUPABASE_DB_USERNAME:postgres}
    password: ${SUPABASE_DB_PASSWORD:password}
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

